### ISSUE TITLE
Different Mastodon accounts for different languages?

### ISSUE THREAD

**Issue by trebmuh** [liberapay/salon#215] opened 2018-03-26 11:44 UTC
https://mastodon.xyz/@Liberapay/99744979562888303

The first answer means (quick translation) :
> @Liberapay I don't to be rude but if you want to toot in several languages, you might want to create different accounts.

This is something which already come to my mind a few times.
Thought?

**Comment by Changaco** [comment] 2018-03-26 11:47
Duplicate of #186.

**Closed as completed by Changaco** 2018-03-26 11:47 UTC
